name: EcoRent CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Start development server
        run: npm run dev &
        env:
          NODE_ENV: test
          MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
          MONGO_PASSWD: ${{ secrets.MONGO_PASSWD }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          PORT: ${{ vars.PORT }}

      - name: Wait for server to be ready
        run: sleep 20

      - name: Run unit tests
        run: npm test

      - name: Run integration tests
        run: npm run test:api
